# Generated by Django 6.1 on 2026-08-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('original_csv', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.CharField(choices=[('az', 'A to Z'), ('za', 'Z to A')], default='az', max_length=2)),
                ('reveal_mode', models.CharField(choices=[('each', 'After every word'), ('end', 'At the end')], default='each', max_length=4)),
                ('status', models.CharField(choices=[('active', 'In progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='active', max_length=10)),
                ('word_ids', models.JSONField(default=list)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vocab.deck')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('word', models.CharField(max_length=200)),
                ('synonym1', models.CharField(max_length=200)),
                ('synonym2', models.CharField(max_length=200)),
                ('antonym1', models.CharField(max_length=200)),
                ('antonym2', models.CharField(max_length=200)),
                ('example', models.TextField(blank=True)),
                ('mark', models.CharField(choices=[('none', 'Not reviewed'), ('green', 'Known'), ('yellow', 'Halfway'), ('red', 'Struggling')], default='none', max_length=10)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.deck')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField(default=0)),
                ('slot', models.CharField(max_length=20)),
                ('given', models.CharField(blank=True, max_length=300)),
                ('expected', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vocab.testsession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vocab.word')),
            ],
            options={
                'ordering': ['question_index', 'id'],
                'unique_together': {('session', 'question_index', 'slot')},
            },
        ),
    ]
