# Generated by Django 6.1 on 2026-08-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='timings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
